apiVersion: v1
kind: Service
metadata:
  name: Prediction-svc
  namespace: mlops
spec:
  selector:
    app: Prediction
    kubernetes.io/name: Prediction
    kubernetes.io/part-of: mlops
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000